version: 2
jobs:
  build:
    environment:
      CC_TEST_REPORTER_ID: 384f1bd23d2f3019bbb0e1e6e2b61ecf24e08680dd5d529311476d2ffd54d3ac
    docker:
      - image: circleci/golang:latest
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      - run:
          name: Pull Dependencies
          command: |
            go get -v -t -d ./...
      - run:
          name: Setup CodeClimate Test Reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - run:
          name: Run Tests
          command: |
            ./cc-test-reporter before-build
            go test -race -coverprofile c.out
            ./cc-test-reporter after-build -t gocov